language: node_js
node_js:
- '12'
env:
  global:
  - DEPLOY_REPOSITORY="git@github.com:konnectors/cozy-konnector-payfit.git"
  # REGISTRY_TOKEN(editor=cozy, app=payfit)
  - secure: cHaVViHbKx9Wk7I/D0AH/vmc0hPyB/Ysnya3gekZHPuA9wKV+yXIKB9fqZxUOT6NZfPNBLBJqpPGHtFMlea+6fNKTOuB7k4+XwBMTPCaEJUazi/yAvg81GCljUV2PC+ZLwoLl898q8OG7UNL2tFmBBv6BWpQi0vy/oHA2/N3g71Y2ukvxUkWfTbNbzUmqYzky0Nap+YSYIrkwM/I58e/DPz1uYAkuGm1vzpEfu565xSCCpnMk2fbKuUe8AbUqU5vTYv1HQdatl7DmaFFkmPnxUUKSnz7MnEI+6VAJZtgT1K+5abDJW8KqzjwBvqJcIOX6CrPiBZEh+cn+SnZh78WxqG3W5Za7/c4tXHaK2E2BSaxJdYOD/zqOhknIGbRUi83hmNwx6t1aP5bPXtd7EsGFGVSuC1qcIXdsLXMOpgq3Bp1WGLmVuPFtSFuWanJuOhymPl62oPm4v2CVyIuy1Fhg8NHOIeABbkjCisBQpbpdnC/DiV4CQfbG4D6pXPrJQFLdXU9Dk8l4Xx+/KSNXihPY2MTIMkvgJdgw9DN3jlRahQtJig4K4c+HHA59F8W3x3zkCS9tRJUEu7dm9SHUVR+5+UkU8sjFjnuu4HaKsgli2OY9BwWisvVkTACuONZVgwDLD3TWhhhQbwsWW28G2/2TR9ADChevQbnQLQYHtExagc=
  # MATTERMOST_HOOK_URL
  - secure: eBWMTELeU53WZ/9WjqxvfQVaOtJ9dgAuM28mfe6RJq5Rhy2dymg810CGOL5VncaaoY1H65jSSsvSkCedD55GGTqiVJKubn8qdm50DSTwl3rwlZE/X8IcdRBwTm0ez5ZikCGSA324dYzP+fXsEng0I1zRC1S84Xq8+lQdp2aBDXvdTWSPUyGg0tMEu5j79gMY7B+qFKcZgC8AdQdXI1wYgoVXCmNZD8qzAOXH1Zpmg5WYqSlNiOnC8gDUJQYqGTfU37upNjY0vMM7Y6BcZ7w5CnRi5e6FtF92lSoj7DClEunokTVvEP63dPWan8WtG18EDSKOIajxJRujvBnSY3PiDXTHlE1Khd4Y0T+/v/RryG/Aq96lGBTnOSZ6uM3NrY4GD9iH5Q3lnQf9kzTQOmWRxGqVP+Ktl5oVRd6F57k+K6vpg45H6StfabGm5FORQ0GtVxIn+tWGXAN+/Ty3mdUzK5IQd0zTWpX/gbp3qj2JOBPotJzT4brmy++ExmgUA+SX+PFbRbnFbFQ6D7zSOw4GjqMTKQlOV4GIuYwaD1EVNHQHEF0CD7ikisLgLMuYsRieC2Wb3oHtXTFEy8fmirYu8zWDsYS/w7MGv96ChRXn8jTrBiERgd2ZIUvf1Z+tSYyhxFq4mAIsnjgCrUgZw8LHWxjYObfUXy/5cUM8UzoEYs0=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_22a6f4525bcb_key -iv $encrypted_22a6f4525bcb_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
