language: node_js
node_js:
- '8'
env:
  global:
  - GH_USER_EMAIL="travis@example.org"
  - GH_USER_NAME="cozy-bot"
  - DEPLOY_REPOSITORY="git@github.com:konnectors/cozy-konnector-payfit.git"
  - secure: cHaVViHbKx9Wk7I/D0AH/vmc0hPyB/Ysnya3gekZHPuA9wKV+yXIKB9fqZxUOT6NZfPNBLBJqpPGHtFMlea+6fNKTOuB7k4+XwBMTPCaEJUazi/yAvg81GCljUV2PC+ZLwoLl898q8OG7UNL2tFmBBv6BWpQi0vy/oHA2/N3g71Y2ukvxUkWfTbNbzUmqYzky0Nap+YSYIrkwM/I58e/DPz1uYAkuGm1vzpEfu565xSCCpnMk2fbKuUe8AbUqU5vTYv1HQdatl7DmaFFkmPnxUUKSnz7MnEI+6VAJZtgT1K+5abDJW8KqzjwBvqJcIOX6CrPiBZEh+cn+SnZh78WxqG3W5Za7/c4tXHaK2E2BSaxJdYOD/zqOhknIGbRUi83hmNwx6t1aP5bPXtd7EsGFGVSuC1qcIXdsLXMOpgq3Bp1WGLmVuPFtSFuWanJuOhymPl62oPm4v2CVyIuy1Fhg8NHOIeABbkjCisBQpbpdnC/DiV4CQfbG4D6pXPrJQFLdXU9Dk8l4Xx+/KSNXihPY2MTIMkvgJdgw9DN3jlRahQtJig4K4c+HHA59F8W3x3zkCS9tRJUEu7dm9SHUVR+5+UkU8sjFjnuu4HaKsgli2OY9BwWisvVkTACuONZVgwDLD3TWhhhQbwsWW28G2/2TR9ADChevQbnQLQYHtExagc=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - latest
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_22a6f4525bcb_key -iv $encrypted_22a6f4525bcb_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
